version: '3'

services:
  v2bx:
    image: v2bx:20250922
    container_name: v2bx
    volumes:
      - $PWD/config:/etc/V2bX
    restart: always
    env_file:
      - conf.env
    network_mode: "host"
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    env_file:
      - conf.env
    network_mode: "host"
    volumes:
      - $PWD/config/cert:/etc/nginx/conf.d/cert
      - $PWD/templates:/etc/nginx/templates
      - $PWD/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - v2bx
    entrypoint: ./wait-for-it.sh localhost:1234 -t 60 -- sh -c "rm -f /etc/nginx/conf.d/default.conf && ./docker-entrypoint.sh nginx -g 'daemon off;'"
