version: '3'

services:
  xrayr:
    image: chuiniubi/xrayr_chuiniubi:latest
    container_name: xrayr
    volumes:
      - $PWD/config:/etc/XrayR
    restart: always
    env_file:
      - conf.env
    network_mode: "host"
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    env_file:
      - conf.env
    network_mode: "host"
    volumes:
      - $PWD/config/cert/certificates:/etc/nginx/conf.d/cert
      - $PWD/templates:/etc/nginx/templates
      - $PWD/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - xrayr
    entrypoint: ./wait-for-it.sh localhost:1234 -t 60 -- sh -c "rm -f /etc/nginx/conf.d/default.conf && ./docker-entrypoint.sh nginx -g 'daemon off;'"      
